spring:
  main:
    lazy-initialization: true # 如果不开启这个，在注入服务时，需要添加@Lazy注解

server:
  port: 7005
#  port: 9002
#  port: 9004

crpc:
  name: TestServer
  ip: 127.0.0.1
  port: 7105
#  port: 9102
#  port: 9104
#  area: BJ
  area: GD
  weight: 1
  center: http://127.0.0.1:7999