spring:
  main:
    lazy-initialization: true # 如果不开启这个，在注入服务时，需要添加@Lazy注解

server:
#  port: 9001
#  port: 9002
  port: 9004

crpc:
  name: DemoServer
  ip: 127.0.0.1
#  port: 9101
#  port: 9102
  port: 9104
  area: BJ
#  area: DG
  weight: 4
  center: http://127.0.0.1:7999