server:
  port: 8000

crpc:
  name: CrpcServer
  ip: 127.0.0.1
  port: 7999
  area: DG
  weight: 1

#server:
#  port: 8003
#
#crpc:
#  name: CrpcServer
#  ip: 127.0.0.1
#  port: 7997
#  area: BJ
#  weight: 3
