server:
  port: 8000

crpc:
  name: CrpcServer
  ip: 127.0.0.1
  port: 7999
#  area: BJ
  area: DG
  weight: 1

#server:
#  port: 8002
#
#crpc:
#  name: CrpcServer
#  ip: 127.0.0.1
#  port: 7998
#  area: BJ
#  weight: 2
